// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC454ElffCd7yQynG5Hr1KO-eMHGv8UC7E",
      authDomain: "easy-mazdoor-559d2.firebaseapp.com",
      projectId: "easy-mazdoor-559d2",
      storageBucket: "easy-mazdoor-559d2.firebasestorage.app",
      messagingSenderId: "206094610648",
      appId: "1:206094610648:web:f16a68864716348e6b67ad",
      measurementId: "G-9249HTEJVW");

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC454ElffCd7yQynG5Hr1KO-eMHGv8UC7E',
    appId: '1:206094610648:web:de6ac20ad8c1a5d46b67ad',
    messagingSenderId: '206094610648',
    projectId: 'easy-mazdoor-559d2',
    authDomain: 'easy-mazdoor-559d2.firebaseapp.com',
    storageBucket: 'easy-mazdoor-559d2.firebasestorage.app',
    measurementId: 'G-RY40XFF3J0',
  );
}
